using System.Globalization;
using System.Security.Cryptography;
using Microsoft.Data.Sqlite;

namespace MinecraftServerManager.Data;

public enum ProductRememberedDeviceStatus
{
    Active,
    Revoked,
    Expired,
}

public enum ProductRememberedDeviceRefreshStatus
{
    Success,
    Invalid,
    Expired,
    Revoked,
    ReplayDetected,
}

public sealed record ProductRememberedDeviceInfo(
    Guid DeviceId,
    string Username,
    string Label,
    ulong Generation,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset LastUsedAtUtc,
    DateTimeOffset IdleExpiresAtUtc,
    DateTimeOffset AbsoluteExpiresAtUtc,
    ProductRememberedDeviceStatus Status,
    DateTimeOffset? RevokedAtUtc,
    string? RevocationReason);

public sealed record ProductRememberedDeviceRefreshResult(
    ProductRememberedDeviceRefreshStatus Status,
    ProductRememberedDeviceInfo? Device = null,
    string? Username = null);

/// <summary>
/// Stores only SHA-256 token hashes. Token secrets and replacement tokens are generated by the
/// Service adapter and are never persisted in plaintext. Reusing the immediately previous token
/// is treated as replay and revokes the device.
/// </summary>
public sealed class ProductRememberedDeviceStore(
    ProductDatabase database,
    TimeProvider? timeProvider = null)
{
    public const int MaximumDevicesPerAccount = 8;
    public const int MaximumDevices = 64;
    public const int SecretHashBytes = 32;
    public static readonly TimeSpan IdleLifetime = TimeSpan.FromDays(90);
    public static readonly TimeSpan AbsoluteLifetime = TimeSpan.FromDays(365);
    private readonly TimeProvider _timeProvider = timeProvider ?? TimeProvider.System;

    public ProductRememberedDeviceInfo Issue(
        string username,
        string label,
        ReadOnlySpan<byte> secretHash)
    {
        if (!ProductRemoteAccountStore.TryNormalizeUsername(username, out var normalizedUsername))
        {
            throw new ArgumentException("Remote username is invalid.", nameof(username));
        }

        label = ValidateLabel(label);
        ValidateHash(secretHash);
        var now = _timeProvider.GetUtcNow();
        var deviceId = Guid.NewGuid();
        var absolute = now.Add(AbsoluteLifetime);
        var idle = Min(now.Add(IdleLifetime), absolute);
        using var connection = database.OpenConnection();
        using var transaction = connection.BeginTransaction();
        try
        {
            EnsureEnabledAccount(connection, transaction, normalizedUsername);
            RevokeExpired(connection, transaction, now);
            if (CountDevices(connection, transaction, username: null) >= MaximumDevices)
            {
                throw new InvalidOperationException("The remembered-device limit has been reached.");
            }

            if (CountDevices(connection, transaction, normalizedUsername) >= MaximumDevicesPerAccount)
            {
                throw new InvalidOperationException("The account remembered-device limit has been reached.");
            }

            using var insert = connection.CreateCommand();
            insert.Transaction = transaction;
            insert.CommandText =
                """
                INSERT INTO remote_remembered_devices(
                    device_id, username, label, generation, secret_hash,
                    previous_generation, previous_secret_hash, created_at_utc, last_used_at_utc,
                    idle_expires_at_utc, absolute_expires_at_utc, revoked_at_utc, revocation_reason)
                VALUES(
                    $device_id, $username, $label, 1, $secret_hash,
                    NULL, NULL, $created, $last_used, $idle_expires, $absolute_expires, NULL, NULL);
                """;
            insert.Parameters.AddWithValue("$device_id", deviceId.ToString("D"));
            insert.Parameters.AddWithValue("$username", normalizedUsername);
            insert.Parameters.AddWithValue("$label", label);
            insert.Parameters.Add("$secret_hash", SqliteType.Blob).Value = secretHash.ToArray();
            insert.Parameters.AddWithValue("$created", FormatUtc(now));
            insert.Parameters.AddWithValue("$last_used", FormatUtc(now));
            insert.Parameters.AddWithValue("$idle_expires", FormatUtc(idle));
            insert.Parameters.AddWithValue("$absolute_expires", FormatUtc(absolute));
            insert.ExecuteNonQuery();
            transaction.Commit();
        }
        catch
        {
            transaction.Rollback();
            throw;
        }

        return GetRequired(deviceId);
    }

    public ProductRememberedDeviceRefreshResult Rotate(
        Guid deviceId,
        ulong generation,
        ReadOnlySpan<byte> presentedSecretHash,
        ReadOnlySpan<byte> replacementSecretHash,
        Guid requestId)
    {
        if (deviceId == Guid.Empty || generation == 0 || requestId == Guid.Empty)
        {
            return new ProductRememberedDeviceRefreshResult(
                ProductRememberedDeviceRefreshStatus.Invalid);
        }

        ValidateHash(presentedSecretHash);
        ValidateHash(replacementSecretHash);
        var now = _timeProvider.GetUtcNow();
        using var connection = database.OpenConnection();
        using var transaction = connection.BeginTransaction();
        try
        {
            var row = ReadRow(connection, transaction, deviceId);
            if (row is null)
            {
                transaction.Commit();
                return new ProductRememberedDeviceRefreshResult(
                    ProductRememberedDeviceRefreshStatus.Invalid);
            }

            if (row.RevokedAtUtc is not null)
            {
                transaction.Commit();
                return new ProductRememberedDeviceRefreshResult(
                    ProductRememberedDeviceRefreshStatus.Revoked,
                    ToInfo(row, now),
                    row.Username);
            }

            if (row.IdleExpiresAtUtc <= now || row.AbsoluteExpiresAtUtc <= now)
            {
                Revoke(connection, transaction, deviceId, now, "expired");
                transaction.Commit();
                var expired = row with { RevokedAtUtc = now, RevocationReason = "expired" };
                return new ProductRememberedDeviceRefreshResult(
                    ProductRememberedDeviceRefreshStatus.Expired,
                    ToInfo(expired, now),
                    row.Username);
            }

            if (row.PreviousGeneration == generation &&
                row.PreviousSecretHash is { } previousHash &&
                CryptographicOperations.FixedTimeEquals(previousHash, presentedSecretHash))
            {
                if (row.LastRefreshRequestId == requestId)
                {
                    transaction.Commit();
                    return new ProductRememberedDeviceRefreshResult(
                        ProductRememberedDeviceRefreshStatus.Success,
                        ToInfo(row, now),
                        row.Username);
                }

                Revoke(connection, transaction, deviceId, now, "replay_detected");
                transaction.Commit();
                var replayed = row with { RevokedAtUtc = now, RevocationReason = "replay_detected" };
                return new ProductRememberedDeviceRefreshResult(
                    ProductRememberedDeviceRefreshStatus.ReplayDetected,
                    ToInfo(replayed, now),
                    row.Username);
            }

            if (row.Generation != generation ||
                !CryptographicOperations.FixedTimeEquals(row.SecretHash, presentedSecretHash))
            {
                transaction.Commit();
                return new ProductRememberedDeviceRefreshResult(
                    ProductRememberedDeviceRefreshStatus.Invalid);
            }

            var nextGeneration = checked(generation + 1);
            var idle = Min(now.Add(IdleLifetime), row.AbsoluteExpiresAtUtc);
            using var update = connection.CreateCommand();
            update.Transaction = transaction;
            update.CommandText =
                """
                UPDATE remote_remembered_devices
                SET previous_generation = generation,
                    previous_secret_hash = secret_hash,
                    generation = $generation,
                    secret_hash = $secret_hash,
                    last_refresh_request_id = $request_id,
                    last_used_at_utc = $last_used,
                    idle_expires_at_utc = $idle_expires
                WHERE device_id = $device_id AND revoked_at_utc IS NULL;
                """;
            update.Parameters.AddWithValue("$generation", checked((long)nextGeneration));
            update.Parameters.Add("$secret_hash", SqliteType.Blob).Value = replacementSecretHash.ToArray();
            update.Parameters.AddWithValue("$request_id", requestId.ToString("D"));
            update.Parameters.AddWithValue("$last_used", FormatUtc(now));
            update.Parameters.AddWithValue("$idle_expires", FormatUtc(idle));
            update.Parameters.AddWithValue("$device_id", deviceId.ToString("D"));
            if (update.ExecuteNonQuery() != 1)
            {
                throw new InvalidOperationException("Remembered device changed concurrently.");
            }

            transaction.Commit();
            var rotated = row with
            {
                PreviousGeneration = row.Generation,
                PreviousSecretHash = row.SecretHash,
                Generation = nextGeneration,
                SecretHash = replacementSecretHash.ToArray(),
                LastRefreshRequestId = requestId,
                LastUsedAtUtc = now,
                IdleExpiresAtUtc = idle,
            };
            return new ProductRememberedDeviceRefreshResult(
                ProductRememberedDeviceRefreshStatus.Success,
                ToInfo(rotated, now),
                row.Username);
        }
        catch
        {
            try
            {
                transaction.Rollback();
            }
            catch (InvalidOperationException)
            {
                // Commit may already have completed before materializing the result.
            }

            throw;
        }
    }

    public IReadOnlyList<ProductRememberedDeviceInfo> List()
    {
        var now = _timeProvider.GetUtcNow();
        using var connection = database.OpenConnection();
        using var command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT device_id, username, label, generation, secret_hash,
                   previous_generation, previous_secret_hash, last_refresh_request_id,
                   created_at_utc, last_used_at_utc, idle_expires_at_utc,
                   absolute_expires_at_utc, revoked_at_utc, revocation_reason
            FROM remote_remembered_devices
            ORDER BY last_used_at_utc DESC, device_id;
            """;
        using var reader = command.ExecuteReader();
        var devices = new List<ProductRememberedDeviceInfo>();
        while (reader.Read())
        {
            devices.Add(ToInfo(ReadRow(reader), now));
        }

        return devices.AsReadOnly();
    }

    public bool Revoke(Guid deviceId, string reason = "administrator_revoked")
    {
        if (deviceId == Guid.Empty || !IsReason(reason))
        {
            return false;
        }

        using var connection = database.OpenConnection();
        using var transaction = connection.BeginTransaction();
        var changed = Revoke(connection, transaction, deviceId, _timeProvider.GetUtcNow(), reason);
        transaction.Commit();
        return changed;
    }

    public int RevokeForAccount(string username, string reason = "account_revoked")
    {
        if (!ProductRemoteAccountStore.TryNormalizeUsername(username, out var normalizedUsername) ||
            !IsReason(reason))
        {
            return 0;
        }

        using var connection = database.OpenConnection();
        using var command = connection.CreateCommand();
        command.CommandText =
            """
            UPDATE remote_remembered_devices
            SET revoked_at_utc = $revoked_at, revocation_reason = $reason
            WHERE username = $username AND revoked_at_utc IS NULL;
            """;
        command.Parameters.AddWithValue("$revoked_at", FormatUtc(_timeProvider.GetUtcNow()));
        command.Parameters.AddWithValue("$reason", reason);
        command.Parameters.AddWithValue("$username", normalizedUsername);
        return command.ExecuteNonQuery();
    }

    public int RevokeAll(string reason = "all_devices_revoked")
    {
        if (!IsReason(reason))
        {
            throw new ArgumentException("Revocation reason is invalid.", nameof(reason));
        }

        using var connection = database.OpenConnection();
        using var command = connection.CreateCommand();
        command.CommandText =
            """
            UPDATE remote_remembered_devices
            SET revoked_at_utc = $revoked_at, revocation_reason = $reason
            WHERE revoked_at_utc IS NULL;
            """;
        command.Parameters.AddWithValue("$revoked_at", FormatUtc(_timeProvider.GetUtcNow()));
        command.Parameters.AddWithValue("$reason", reason);
        return command.ExecuteNonQuery();
    }

    private ProductRememberedDeviceInfo GetRequired(Guid deviceId)
    {
        using var connection = database.OpenConnection();
        var row = ReadRow(connection, transaction: null, deviceId)
            ?? throw new KeyNotFoundException("Remembered device was not found.");
        return ToInfo(row, _timeProvider.GetUtcNow());
    }

    private static DeviceRow? ReadRow(
        SqliteConnection connection,
        SqliteTransaction? transaction,
        Guid deviceId)
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText =
            """
            SELECT device_id, username, label, generation, secret_hash,
                   previous_generation, previous_secret_hash, last_refresh_request_id,
                   created_at_utc, last_used_at_utc, idle_expires_at_utc,
                   absolute_expires_at_utc, revoked_at_utc, revocation_reason
            FROM remote_remembered_devices
            WHERE device_id = $device_id;
            """;
        command.Parameters.AddWithValue("$device_id", deviceId.ToString("D"));
        using var reader = command.ExecuteReader();
        return reader.Read() ? ReadRow(reader) : null;
    }

    private static DeviceRow ReadRow(SqliteDataReader reader)
        => new(
            Guid.ParseExact(reader.GetString(0), "D"),
            reader.GetString(1),
            reader.GetString(2),
            checked((ulong)reader.GetInt64(3)),
            (byte[])reader[4],
            reader.IsDBNull(5) ? null : checked((ulong)reader.GetInt64(5)),
            reader.IsDBNull(6) ? null : (byte[])reader[6],
            reader.IsDBNull(7) ? null : Guid.ParseExact(reader.GetString(7), "D"),
            ParseUtc(reader.GetString(8)),
            ParseUtc(reader.GetString(9)),
            ParseUtc(reader.GetString(10)),
            ParseUtc(reader.GetString(11)),
            reader.IsDBNull(12) ? null : ParseUtc(reader.GetString(12)),
            reader.IsDBNull(13) ? null : reader.GetString(13));

    private static ProductRememberedDeviceInfo ToInfo(DeviceRow row, DateTimeOffset now)
    {
        var status = string.Equals(row.RevocationReason, "expired", StringComparison.Ordinal) ||
                     (row.RevokedAtUtc is null &&
                      (row.IdleExpiresAtUtc <= now || row.AbsoluteExpiresAtUtc <= now))
            ? ProductRememberedDeviceStatus.Expired
            : row.RevokedAtUtc is not null
                ? ProductRememberedDeviceStatus.Revoked
                : ProductRememberedDeviceStatus.Active;
        return new ProductRememberedDeviceInfo(
            row.DeviceId,
            row.Username,
            row.Label,
            row.Generation,
            row.CreatedAtUtc,
            row.LastUsedAtUtc,
            row.IdleExpiresAtUtc,
            row.AbsoluteExpiresAtUtc,
            status,
            row.RevokedAtUtc,
            row.RevocationReason);
    }

    private static void EnsureEnabledAccount(
        SqliteConnection connection,
        SqliteTransaction transaction,
        string username)
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = "SELECT enabled FROM remote_accounts WHERE username = $username;";
        command.Parameters.AddWithValue("$username", username);
        var value = command.ExecuteScalar();
        if (value is null)
        {
            throw new KeyNotFoundException("Remote account was not found.");
        }

        if (Convert.ToInt32(value, CultureInfo.InvariantCulture) != 1)
        {
            throw new InvalidOperationException("Remote account is disabled.");
        }
    }

    private static int CountDevices(
        SqliteConnection connection,
        SqliteTransaction transaction,
        string? username)
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = username is null
            ? "SELECT COUNT(*) FROM remote_remembered_devices WHERE revoked_at_utc IS NULL;"
            : "SELECT COUNT(*) FROM remote_remembered_devices WHERE username = $username AND revoked_at_utc IS NULL;";
        if (username is not null)
        {
            command.Parameters.AddWithValue("$username", username);
        }

        return Convert.ToInt32(command.ExecuteScalar(), CultureInfo.InvariantCulture);
    }

    private static void RevokeExpired(
        SqliteConnection connection,
        SqliteTransaction transaction,
        DateTimeOffset now)
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText =
            """
            UPDATE remote_remembered_devices
            SET revoked_at_utc = $now, revocation_reason = 'expired'
            WHERE revoked_at_utc IS NULL
              AND (idle_expires_at_utc <= $now OR absolute_expires_at_utc <= $now);
            """;
        command.Parameters.AddWithValue("$now", FormatUtc(now));
        command.ExecuteNonQuery();
    }

    private static bool Revoke(
        SqliteConnection connection,
        SqliteTransaction transaction,
        Guid deviceId,
        DateTimeOffset now,
        string reason)
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText =
            """
            UPDATE remote_remembered_devices
            SET revoked_at_utc = $revoked_at, revocation_reason = $reason
            WHERE device_id = $device_id AND revoked_at_utc IS NULL;
            """;
        command.Parameters.AddWithValue("$revoked_at", FormatUtc(now));
        command.Parameters.AddWithValue("$reason", reason);
        command.Parameters.AddWithValue("$device_id", deviceId.ToString("D"));
        return command.ExecuteNonQuery() == 1;
    }

    private static string ValidateLabel(string value)
    {
        value = value?.Trim() ?? string.Empty;
        if (value.Length is < 1 or > 64 || value.Any(char.IsControl))
        {
            throw new ArgumentException("Remembered-device label is invalid.", nameof(value));
        }

        return value;
    }

    private static void ValidateHash(ReadOnlySpan<byte> value)
    {
        if (value.Length != SecretHashBytes)
        {
            throw new ArgumentException("Remembered-device secret hash is invalid.");
        }
    }

    private static bool IsReason(string? value)
        => value is { Length: > 0 and <= 64 } &&
           value.All(character =>
               character is >= 'a' and <= 'z' or >= '0' and <= '9' or '_' or '-');

    private static DateTimeOffset Min(DateTimeOffset first, DateTimeOffset second)
        => first <= second ? first : second;

    private static string FormatUtc(DateTimeOffset value)
        => value.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture);

    private static DateTimeOffset ParseUtc(string value)
        => DateTimeOffset.Parse(
            value,
            CultureInfo.InvariantCulture,
            DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal);

    private sealed record DeviceRow(
        Guid DeviceId,
        string Username,
        string Label,
        ulong Generation,
        byte[] SecretHash,
        ulong? PreviousGeneration,
        byte[]? PreviousSecretHash,
        Guid? LastRefreshRequestId,
        DateTimeOffset CreatedAtUtc,
        DateTimeOffset LastUsedAtUtc,
        DateTimeOffset IdleExpiresAtUtc,
        DateTimeOffset AbsoluteExpiresAtUtc,
        DateTimeOffset? RevokedAtUtc,
        string? RevocationReason);
}
